config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :inicios

  root 'welcome#index'

end

app/models/inicio.rb
class Inicio < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicios_helper.rb
module IniciosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inicios/_form.html.erb
<%= form_for(@inicio) do |f| %>
  <% if @inicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inicio.errors.count, "error") %> prohibited this inicio from being saved:</h2>

      <ul>
      <% @inicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inicios/edit.html.erb
<h1>Editing Inicio</h1>

<%= render 'form' %>

<%= link_to 'Show', @inicio %> |
<%= link_to 'Back', inicios_path %>

app/views/inicios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inicios</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inicios.each do |inicio| %>
      <tr>
        <td><%= link_to 'Show', inicio %></td>
        <td><%= link_to 'Edit', edit_inicio_path(inicio) %></td>
        <td><%= link_to 'Destroy', inicio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inicio', new_inicio_path %>

app/views/inicios/new.html.erb
<h1>New Inicio</h1>

<%= render 'form' %>

<%= link_to 'Back', inicios_path %>

app/views/inicios/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inicio_path(@inicio) %> |
<%= link_to 'Back', inicios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>login</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>

<p class="navbar-text pull-right">
		<% if user_signed_in? %>
		  entrar con: <strong><%= current_user.email %></strong>.
		  <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %> |
		  <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
		  <%= link_to "registrar", new_user_registration_path, :class => 'navbar-link'  %> |
		  <%= link_to "Salir", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<!--es la es la pagina principal 
donde vamos a distribuir las demas ventanas-->
<h1>Inicio</h1>
<p>Pagina principal</p>